sudo: false
language: java
dist: trusty

before_cache:
  # No sense in caching current build artifacts
  rm -rf $HOME/.m2/repository/com/github/vlsi

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

install:
  - mvn -Djavac.target=$TRGT install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -Djavac.target=$TRGT test -B

matrix:
  include:
  - jdk: oraclejdk8
    env:
    - JDK=8
    - TRGT=1.5
  - jdk: oraclejdk11
    env:
    - JDK=11
    - TRGT=1.6
